name: CI/CD workflow for Maven Build and SonarCloud Scan

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - demo_final
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build and SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -f ./crud_rest_db/pom.xml clean verify sonar:sonar \
            -Dsonar.projectKey=Aritz94318_pbl5_Web \
            -Dsonar.organization=aritz94318 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=$SONAR_TOKEN \
            -Dsonar.projectVersion=${{ github.run_number }} \
            -Dsonar.qualitygate.wait=true \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }} || true
            
      - name: List target directory
        run: ls -lh ./crud_rest_db/target


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-docker.pkg.dev

      - name: Build & Push Docker image
        run: docker build -t europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pinkalert/crud-rest-db ./crud_rest_db && docker push europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pinkalert/crud-rest-db
      - name: Check GCP configuration
        run: |
         gcloud config list
         gcloud auth list
         gcloud projects describe ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy crud-rest-db \
           --image europe-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/pinkalert/crud-rest-db \
           --region ${{ secrets.GCP_REGION }} \
           --platform managed \
           --memory=1Gi \
            --allow-unauthenticated \
            --add-cloudsql-instances ${{ secrets.CLOUDSQL_INSTANCE }} \
            --set-env-vars \
          DB_NAME=pinkalert,\
          DB_USER=${{ secrets.DB_USER }},\
          DB_PASS=${{ secrets.DB_PASS }},\
          INSTANCE_CONNECTION_NAME=${{ secrets.CLOUDSQL_INSTANCE }}
